############### Simple Jenkinsfile for CICD Pipeline ###############

pipeline {
    agent any
    stages {
        stage (" GIT CHECKOUT") {
            steps {
                echo " GIT CLONE IS FINISHED"
            }
        }// stage1
        stage (" Junit") {
            steps {
                echo " Junit IS FINISHED"
            }
        }// stage2
        stage (" Build") {
            steps {
                echo " build IS FINISHED"
            }
        }// stage3
    }//stages
}//Pipeline

############# End of Jenkinsfile #############

############### Java App CICD simple Jenkinsfile ###############
pipeline {
    agent any 

    stages {
        stage("GIT-CHECKOUT") {
            steps {
                git branch: 'main', url: 'https://github.com/vickydevo/springboot.git' 
            }
        }

        stage("JUnit-test") {
            steps {
                sh 'mvn clean test'
            }
        }

        stage("Maven-Build") {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage("Docker-image") {
            steps {
                // Using sh to print the system user
                sh 'echo "Running as user: $(whoami)"'
                sh 'docker build -t spring:v1 .'
            }
        }

        stage("Docker-Run") {
            steps {
                sh 'docker run -d -p 8081:8081 --name springapp spring:v1'
                }
            }
        }
    }

    ############# End of Java App CICD simple Jenkinsfile #############}



